on:
  push:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make module.tar.gz
    # publish for ARM devices
    - name: upload
      if: ${{ github.event_name == 'release' }}
      uses: viamrobotics/upload-module@main
      with:
        module-path: module.tar.gz
        platform: linux/arm64
        version: ${{ github.ref_name }}
        cli-config-secret: ${{ secrets.cli_config }}
    # publish for Intel devices
    - name: upload
      if: ${{ github.event_name == 'release' }}
      uses: viamrobotics/upload-module@main
      with:
        module-path: module.tar.gz
        platform: linux/amd64
        version: ${{ github.ref_name }}
        cli-config-secret: ${{ secrets.cli_config }}
