on:
  push:
  release:
    types: [published]

env:
  VERSION: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make module.tar.gz
    - name: upload ARM
      if: ${{ github.event_name == 'release' }}
      uses: viamrobotics/upload-module@main
      with:
        module-path: module.tar.gz
        platform: linux/arm64
        version: ${{ env.VERSION }}
        cli-config-secret: ${{ secrets.cli_config }}
    - name: upload x86
      if: ${{ github.event_name == 'release' }}
      uses: viamrobotics/upload-module@main
      with:
        module-path: module.tar.gz
        platform: linux/amd64
        version: ${{ env.VERSION }}
        cli-config-secret: ${{ secrets.cli_config }}
